FROM golang:1.9.1 as builder

WORKDIR /go/src/github.com/nicollet/kubernetes/gcd/api
COPY api .
COPY pb ../pb

RUN go-wrapper download # go get -v ./...
RUN CGO_ENABLED=0 GOOS=linux go-wrapper install # go install -v ./...

FROM alpine:latest
RUN apk --no-cache add ca-certificates
WORKDIR /root/
COPY --from=builder /go/bin/api .
CMD ["./api"]
