FROM golang:1.9.1 as builder

WORKDIR /go/src/github.com/nicollet/kubernetes/gcd/gcd
COPY gcd .
COPY pb ../pb

RUN go-wrapper download
RUN CGO_ENABLED=0 GOOS=linux go-wrapper install

FROM alpine:latest
RUN apk --no-cache add ca-certificates
WORKDIR /root
COPY --from=builder /go/bin/gcd .
RUN ls
CMD ["./gcd"]
